[package]
name = "perf-test"
version = "0.1.0"
description = "Moonbeam Performance Tests"
authors = ["PureStake"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
hex = "0.4.3"
async-io = "1.3"
futures = { version = "0.3.1", features = ["compat"] }
libsecp256k1 = { version = "0.5" }
ethereum = { version = "0.9.0" }
rlp = { version = "0.5" }
sha3 = { version = "0.8" }

# TODO: handle different runtime builds
moonbase-runtime = { path = "../../runtime/moonbase" }

sc-cli = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-service = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-client-db = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-executor = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-consensus-manual-seal = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-basic-authorship = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sc-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-timestamp = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-api = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-externalities = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-keystore = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
sp-state-machine = { git = "https://github.com/purestake/substrate", branch = "crystalin-v0.9.9-block-response-length" }
nimbus-primitives = { git = "https://github.com/purestake/cumulus", branch = "notlesh-nimbus-v0.9.9-block-response-length" }
fp-rpc = { git = "https://github.com/purestake/frontier", branch = "notlesh-v0.9.9-block-response-length" }
fp-evm = { git = "https://github.com/purestake/frontier", branch = "notlesh-v0.9.9-block-response-length" }
pallet-ethereum = { git = "https://github.com/purestake/frontier", branch = "notlesh-v0.9.9-block-response-length" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/purestake/cumulus", branch = "notlesh-nimbus-v0.9.9-block-response-length" }
fc-consensus = { git = "https://github.com/purestake/frontier", branch = "notlesh-v0.9.9-block-response-length" }

service = { package = "moonbeam-service", path = "../service", default-features = false }
cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt", default-features = false }
